const mongoose = require("mongoose");
const Storage = require("./models/Storage");
require("dotenv").config();

const storageProducts = [
  {
    name: "1TB Surveillance HDD",
    description:
      "WD Purple / Seagate SkyHawk series - Perfect for small to medium CCTV systems with 24×7 recording",
    brand: "WD/Seagate",
    model: "Purple/SkyHawk",
    price: 3499,
    mrp: 4499,
    rating: 4.7,
    reviews: 234,
    images: [],
    features: [
      "1TB capacity for 30 days recording (4 cameras)",
      "Optimized for 24×7 surveillance operation",
      "AllFrame AI technology reduces frame loss",
      "3-year manufacturer warranty",
      "Low power consumption",
      "SATA III 6Gb/s interface",
    ],
    badge: "bestseller",
    specifications: {
      capacity: "1TB",
      type: "Surveillance HDD",
      interface: "SATA III 6Gb/s",
      rpm: "5400 RPM",
      cache: "64MB",
      workload: "180TB/year",
      warranty: "3 Years",
    },
    inStock: true,
  },
  {
    name: "2TB Surveillance HDD",
    description:
      "Enterprise-grade storage designed for DVR/NVR systems with multiple camera streams",
    brand: "WD/Seagate",
    model: "Purple/SkyHawk",
    price: 5999,
    mrp: 7499,
    rating: 4.8,
    reviews: 189,
    images: [],
    features: [
      "2TB capacity for 60 days recording (4 cameras)",
      "Supports up to 64 HD cameras",
      "180TB/year workload rating",
      "AllFrame technology for smooth playback",
      "Tarnish-resistant components",
      "Extended operating temperature",
    ],
    badge: "",
    specifications: {
      capacity: "2TB",
      type: "Surveillance HDD",
      interface: "SATA III 6Gb/s",
      rpm: "5400 RPM",
      cache: "64MB",
      workload: "180TB/year",
      warranty: "3 Years",
    },
    inStock: true,
  },
  {
    name: "4TB Surveillance HDD",
    description:
      "High-capacity storage solution for large surveillance systems with extended retention",
    brand: "WD/Seagate",
    model: "Purple/SkyHawk",
    price: 9999,
    mrp: 12999,
    rating: 4.9,
    reviews: 156,
    images: [],
    features: [
      "4TB capacity for 90+ days recording",
      "Supports 64+ cameras simultaneously",
      "AllFrame 2.0 AI technology",
      "RV sensors for multi-bay systems",
      "Optimized for NVR/DVR",
      "Low acoustic signature",
    ],
    badge: "featured",
    specifications: {
      capacity: "4TB",
      type: "Surveillance HDD",
      interface: "SATA III 6Gb/s",
      rpm: "5400 RPM",
      cache: "128MB",
      workload: "180TB/year",
      warranty: "3 Years",
    },
    inStock: true,
  },
  {
    name: "6TB Surveillance HDD",
    description:
      "Professional storage solution for enterprise surveillance deployments",
    brand: "WD/Seagate",
    model: "Purple/SkyHawk",
    price: 14999,
    mrp: 18999,
    rating: 4.8,
    reviews: 98,
    images: [],
    features: [
      "6TB capacity for 120+ days recording",
      "90+ days continuous recording",
      "Enhanced reliability for mission-critical applications",
      "Advanced firmware for surveillance workloads",
      "RV sensors included",
      "Extended 5-year warranty available",
    ],
    badge: "",
    specifications: {
      capacity: "6TB",
      type: "Surveillance HDD",
      interface: "SATA III 6Gb/s",
      rpm: "5400 RPM",
      cache: "256MB",
      workload: "180TB/year",
      warranty: "3 Years",
    },
    inStock: true,
  },
  {
    name: "8TB Surveillance HDD",
    description:
      "Maximum capacity enterprise storage for large-scale surveillance installations",
    brand: "WD/Seagate",
    model: "Purple/SkyHawk Pro",
    price: 19999,
    mrp: 25999,
    rating: 4.9,
    reviews: 76,
    images: [],
    features: [
      "8TB capacity for 150+ days recording",
      "Supports 128+ camera streams",
      "256MB cache for smooth performance",
      "CMR (Conventional Magnetic Recording)",
      "Purpose-built for surveillance",
      "Industry-leading reliability",
    ],
    badge: "new",
    specifications: {
      capacity: "8TB",
      type: "Surveillance HDD",
      interface: "SATA III 6Gb/s",
      rpm: "7200 RPM",
      cache: "256MB",
      workload: "300TB/year",
      warranty: "3 Years",
    },
    inStock: true,
  },
  {
    name: "256GB MicroSD Card (High Endurance)",
    description:
      "High-endurance microSD designed for continuous recording in IP cameras",
    brand: "Samsung/SanDisk",
    model: "Pro Endurance",
    price: 2499,
    mrp: 3499,
    rating: 4.6,
    reviews: 312,
    images: [],
    features: [
      "256GB capacity",
      "U3/V30 speed class for 4K recording",
      "High endurance for 24×7 recording",
      "Water, shock, and X-ray proof",
      "10-year limited warranty",
      "Perfect for edge recording",
    ],
    badge: "",
    specifications: {
      capacity: "256GB",
      type: "MicroSDXC",
      interface: "UHS-I U3, V30",
      rpm: "N/A",
      cache: "N/A",
      workload: "High Endurance",
      warranty: "10 Years",
    },
    inStock: true,
  },
  {
    name: "128GB MicroSD Card (High Endurance)",
    description:
      "Reliable microSD for IP cameras with edge recording capability",
    brand: "Samsung/SanDisk",
    model: "Pro Endurance",
    price: 1499,
    mrp: 1999,
    rating: 4.5,
    reviews: 267,
    images: [],
    features: [
      "128GB capacity",
      "U3 speed class",
      "Built for continuous recording",
      "Temperature resistant",
      "5-year warranty",
      "Compatible with all IP cameras",
    ],
    badge: "",
    specifications: {
      capacity: "128GB",
      type: "MicroSDXC",
      interface: "UHS-I U3",
      rpm: "N/A",
      cache: "N/A",
      workload: "High Endurance",
      warranty: "5 Years",
    },
    inStock: true,
  },
  {
    name: "1TB Portable SSD",
    description: "Fast portable SSD for quick backup and footage transfer",
    brand: "Samsung/SanDisk",
    model: "T7/Extreme Pro",
    price: 8999,
    mrp: 11999,
    rating: 4.7,
    reviews: 134,
    images: [],
    features: [
      "1TB ultra-fast storage",
      "USB 3.2 Gen 2 (up to 1050MB/s)",
      "Compact and durable design",
      "Password protection with 256-bit AES encryption",
      "Cross-platform compatibility",
      "3-year warranty",
    ],
    badge: "new",
    specifications: {
      capacity: "1TB",
      type: "Portable SSD",
      interface: "USB 3.2 Gen 2",
      rpm: "N/A (SSD)",
      cache: "N/A",
      workload: "N/A",
      warranty: "3 Years",
    },
    inStock: true,
  },
  {
    name: "HDD Mounting Bracket Kit",
    description:
      'Universal mounting brackets and screws for 3.5" HDDs in NVR/DVR',
    brand: "Generic",
    model: "Universal",
    price: 299,
    mrp: 499,
    rating: 4.4,
    reviews: 89,
    images: [],
    features: [
      'Fits all standard 3.5" HDDs',
      "Includes mounting screws",
      "Anti-vibration rubber pads",
      "Easy installation",
      "Compatible with most NVRs/DVRs",
      "Durable metal construction",
    ],
    badge: "",
    specifications: {
      capacity: "N/A",
      type: "Mounting Bracket",
      interface: "N/A",
      rpm: "N/A",
      cache: "N/A",
      workload: "N/A",
      warranty: "1 Year",
    },
    inStock: true,
  },
  {
    name: "SATA Data Cable (18 inch) - Pack of 2",
    description: "High-quality SATA III cables for connecting HDDs to NVR/DVR",
    brand: "Generic",
    model: "SATA III",
    price: 199,
    mrp: 349,
    rating: 4.5,
    reviews: 156,
    images: [],
    features: [
      "Pack of 2 SATA cables",
      "18-inch length",
      "SATA III 6Gb/s support",
      "Gold-plated connectors",
      "Locking latch design",
      "Flexible and durable",
    ],
    badge: "",
    specifications: {
      capacity: "N/A",
      type: "SATA Cable",
      interface: "SATA III 6Gb/s",
      rpm: "N/A",
      cache: "N/A",
      workload: "N/A",
      warranty: "1 Year",
    },
    inStock: true,
  },
];

mongoose
  .connect(process.env.MONGODB_URI)
  .then(async () => {
    console.log("MongoDB Connected for seeding storage products...");

    // Clear existing storage products
    await Storage.deleteMany({});
    console.log("Cleared existing storage products");

    // Insert new storage products
    const result = await Storage.insertMany(storageProducts);
    console.log(`Seeded ${result.length} storage products successfully`);

    process.exit(0);
  })
  .catch((err) => {
    console.error("Error:", err);
    process.exit(1);
  });
